# Definimos las variables de la base de datos una sola vez
x-db-env: &db-env
  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_colegio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: alumno123

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: db_colegio
      MYSQL_ROOT_PASSWORD: alumno123
    ports:
      - "3306:3306"
    networks:
      - colegio-net
    volumes:
      - ./db_data:/var/lib/mysql# He ajustado esto para persistencia real en EC2
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ms-academico:
    image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/ms-academico:latest
    ports: ["8080:8080"]
    networks: ["colegio-net"]
    depends_on:
      db: { condition: service_healthy }
    environment: *db-env
    restart: unless-stopped

  ms-asistencia:
    image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/ms-asistencia:latest
    ports: ["8081:8080"]
    networks: ["colegio-net"]
    depends_on:
      db: { condition: service_healthy }
    environment: *db-env
    restart: unless-stopped

  ms-comunicaciones:
    image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/ms-comunicaciones:latest
    ports: ["8083:8080"]
    networks: ["colegio-net"]
    depends_on:
      db: { condition: service_healthy }
    environment: *db-env
    restart: unless-stopped

  bff-service:
    image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/bff-service:latest
    ports: ["8082:8080"]
    networks: ["colegio-net"]
    depends_on:
      ms-academico: { condition: service_started }
      ms-asistencia: { condition: service_started }
      ms-comunicaciones: { condition: service_started }
    environment:
      URL_ACADEMICO: "http://ms-academico:8080/api/estudiantes"
      URL_ASISTENCIA: "http://ms-asistencia:8080/api/asistencia"
      URL_COMUNICACIONES: "http://ms-comunicaciones:8080/api/comunicaciones/resumen"
    restart: unless-stopped

  frontend:
    image: 471112675233.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    ports: ["3000:80"]
    networks: ["colegio-net"]
    depends_on:
      bff-service: { condition: service_started }
    restart: unless-stopped

networks:
  colegio-net:
    driver: bridge